export const destinationData =[
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Russia.webp", title:"Study in Russia", category:"Destination", href:"/studyDestinations/study-mbbs-in-russia",
      description:"Study MBBS in Russia at top medical universities with globally recognized degrees and affordable tuition fees.",
    },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/China.webp", title:"Study in China", category:"Destination",href:"/studyDestinations/study-mbbs-in-china",
        description:"Earn a globally recognized MBBS degree in China with advanced infrastructure, affordable fees, and world-class faculty.",
      },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Germany.webp", title:"Study in Germany", category:"Destination", href:"/#",
      description:"Explore world-class education in Germany with tuition-free universities, research opportunities, and strong career prospects.",
    },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Hungary.webp", title:"Study in Hungary", category:"Destination",href:"/#",
      description:"Pursue quality education in Hungary, known for its affordable tuition fees, vibrant student life, and EU-recognized degrees.",
    },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/UK.webp", title:"Study in UK", category:"Destination",href:"/#",
      description:"Experience top-ranked universities, a diverse learning environment, and excellent career opportunities in the UK.",
    },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Tajikistan.webp", title:"Study in Tajikistan", category:"Destination", href:"/#",
      description:"Get an affordable and high-quality MBBS degree in Tajikistan with globally accepted medical programs.",
    },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Kyrgyzstan.webp", title:"Study in Kyrgyzstan", category:"Destination",href:"/#",
      description:"Study MBBS in Kyrgyzstan with low tuition fees, English-medium instruction, and MCI/WHO-approved universities.",
    },  
    
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Australia.webp", title:"Study in Australia", category:"Destination",href:"/#",
      description:"Choose MBBS in Bangladesh for quality medical education with a curriculum similar to India and affordable costs.",
    },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Ukraine.webp", title:"Study in Ukraine", category:"Destination",href:"/#",
      description:"Study MBBS in Nepal with an Indian-similar syllabus, affordable fees, and high-quality medical training.",
    },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Georgia.webp", title:"Study in Georgia", category:"Destination",href:"/#",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Uzbekistan.webp", title:"Study in Uzbekistan", category:"Destination",href:"/#",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.",
    },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Kazakhstan.webp", title:"Study in Kazakhstan", category:"Destination",href:"/#",
        description:"Kazakhstan offers low-cost MBBS programs with globally recognized degrees and modern medical infrastructure.",
    },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Nepal.webp", title:"Study in Nepal", category:"Destination",href:"/#",
        description:"Secure an MBBS degree in Uzbekistan with English-medium programs and affordable tuition at recognized universities.",
    },
    {image:"/assets/Images/CountryBlogs/studyDestinationCard/Bangladesh.webp", title:"Study in Bangladesh", category:"Destination",href:"/#",
        description:"Study MBBS in Georgia at top-ranked universities with European education standards and modern facilities.",
    }
  ]